import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "../styles/_global.scss";
import Navbar from "../common/components/Navbar/Navbar";

const jura = Jura({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jura.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
